# подключение базы данных
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  # при запуске приложения, создавал новую БД (чтобы обновлял, пишем update)
  jpa:
    hibernate:
      ddl-auto: none
      # выводит в консоль все действия, которые происходят с БД
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  sql:
    init:
      mode: always
      continue-on-error: true

  security:
    user:
      password: password

server:
  port: 8083

jwt:
  secret: secret
