# подключение базы данных
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  # при запуске приложения, создавал новую БД (чтобы обновлял, пишем update)
  jpa:
    hibernate:
      ddl-auto: update
      # выводит в консоль все действия, которые происходят с БД
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8083